# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["zeeshan.ashraf@optimizely.com"]
description = "A basic starter kit for Fastly's Compute@Edge with Optimizely built in."
language = "javascript"
manifest_version = 2
name = "Optimizely Full Stack"

[setup.backends]
  
  [setup.backends.optlycdn]
    address = "cdn.optimizely.com"
    port = 443

  [setup.backends.optlylogx]
    address = "logx.optimizely.com"
    port = 443

[local_server.backends]

    [local_server.backends.optlycdn]
      url = "https://cdn.optimizely.com"
    
    [local_server.backends.optlylogx]
      url = "https://logx.optimizely.com"
